In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/who-is-the-real-winner/sample_submission.csv
/kaggle/input/who-is-the-real-winner/train.csv
/kaggle/input/who-is-the-real-winner/test.csv


In [2]:
train_data = pd.read_csv("/kaggle/input/who-is-the-real-winner/train.csv")

In [3]:
train_data.columns

Index(['ID', 'Candidate', 'Constituency ∇', 'Party', 'Criminal Case',
       'Total Assets', 'Liabilities', 'state', 'Education'],
      dtype='object')

In [4]:
train_data.isnull().sum()

ID                0
Candidate         0
Constituency ∇    0
Party             0
Criminal Case     0
Total Assets      0
Liabilities       0
state             0
Education         0
dtype: int64

In [5]:
train_data['Education'].unique()

array(['8th Pass', '12th Pass', 'Post Graduate', 'Graduate Professional',
       'Graduate', '10th Pass', 'Others', 'Doctorate', 'Literate',
       '5th Pass'], dtype=object)

In [6]:
train_data['Total Assets'].unique()

array(['211 Crore+', '1 Crore+', '7 Crore+', '9 Crore+', '2 Crore+',
       '3 Crore+', '5 Crore+', '22 Crore+', '0', '8 Crore+', '12 Crore+',
       '63 Crore+', '11 Lac+', '31 Crore+', '60 Lac+', '11 Crore+',
       '17 Crore+', '18 Lac+', '41 Crore+', '4 Crore+', '6 Crore+',
       '95 Lac+', '21 Crore+', '10 Crore+', '19 Crore+', '5 Lac+',
       '64 Crore+', '50 Lac+', '8 Lac+', '57 Lac+', '16 Lac+', '90 Lac+',
       '37 Lac+', '14 Crore+', '40 Crore+', '21 Lac+', '82 Lac+',
       '79 Lac+', '13 Crore+', '96 Lac+', '159 Crore+', '73 Thou+',
       '80 Crore+', '78 Lac+', '27 Crore+', '94 Lac+', '20 Crore+',
       '49 Lac+', '19 Lac+', '27 Lac+', '65 Crore+', '81 Crore+',
       '6 Lac+', '66 Lac+', '35 Crore+', '28 Lac+', '109 Crore+',
       '10 Lac+', '13 Lac+', '38 Lac+', '64 Lac+', '39 Lac+', '43 Lac+',
       '25 Crore+', '91 Lac+', '22 Lac+', '12 Lac+', '49 Crore+',
       '70 Lac+', '36 Lac+', '30 Crore+', '62 Lac+', '65 Lac+', '26 Lac+',
       '67 Lac+', '69 Crore+', '

In [7]:
train_data['Liabilities'].unique()

array(['2 Crore+', '0', '22 Lac+', '24 Lac+', '61 Lac+', '29 Lac+',
       '35 Lac+', '10 Lac+', '1 Lac+', '15 Lac+', '73 Lac+', '5 Lac+',
       '6 Lac+', '1 Crore+', '4 Lac+', '42 Lac+', '4 Crore+', '3 Lac+',
       '18 Lac+', '17 Crore+', '39 Lac+', '26 Lac+', '8 Lac+', '3 Crore+',
       '7 Crore+', '9 Lac+', '28 Lac+', '14 Lac+', '37 Lac+', '47 Lac+',
       '6 Crore+', '23 Lac+', '90 Lac+', '7 Lac+', '53 Lac+', '75 Lac+',
       '44 Lac+', '60 Thou+', '21 Lac+', '55 Lac+', '17 Lac+', '2 Lac+',
       '49 Lac+', '91 Lac+', '11 Crore+', '16 Lac+', '89 Lac+', '12 Lac+',
       '62 Lac+', '34 Lac+', '37 Crore+', '15 Crore+', '20 Lac+',
       '70 Lac+', '61 Thou+', '32 Lac+', '50 Lac+', '48 Lac+',
       '43 Crore+', '5 Crore+', '31 Lac+', '30 Lac+', '11 Lac+',
       '80 Lac+', '46 Lac+', '60 Lac+', '9 Crore+', '9 Hund+', '30 Thou+',
       '99 Lac+', '46 Thou+', '59 Lac+', '22 Crore+', '95 Lac+',
       '13 Lac+', '96 Lac+', '27 Lac+', '36 Crore+', '19 Lac+', '57 Lac+',
       '82 

In [8]:
def convert_to_numeric(value):
    value = str(value)
    if value.endswith('Crore+'):
        return float(value.replace(' Crore+', '')) * 10000000
    elif value.endswith('Lac+'):
        return float(value.replace(' Lac+', '')) * 100000
    elif value.endswith('Thou+'):
        return float(value.replace(' Thou+', '')) * 1000
    elif value.endswith('Crore'):
        return float(value.replace(' Crore', '')) * 10000000
    elif value.endswith('Lac'):
        return float(value.replace(' Lac', '')) * 100000
    elif value.endswith('Thou'):
        return float(value.replace(' Thou', '')) * 1000
    elif value.endswith('Lac'):
        return float(value.replace(' Lac', '')) * 100000
    elif value.endswith('Crore'):
        return float(value.replace(' Crore', '')) * 10000000
    elif value.endswith('Hund+'):
        return float(value.replace(' Hund+', '')) * 100
    elif value.endswith('Hund'):
        return float(value.replace(' Hund', '')) * 100
    else:
        return float(value.replace('+', ''))
    
data1 = train_data['Total Assets']
train_data['Total Assets'] = [convert_to_numeric(value) for value in data1]
data2 = train_data['Liabilities']
train_data['Liabilities'] = [convert_to_numeric(value) for value in data2]

In [9]:
train_data['Total Assets'].dtype

dtype('float64')

In [10]:
train_data['Liabilities'].dtype

dtype('float64')

In [11]:
train_data['Debt Ratio']  = train_data['Total Assets']/train_data['Liabilities']

In [12]:
train_data['Criminal Case'].dtype

dtype('int64')

In [13]:
train_data['state'].unique()

array(['TAMIL NADU', 'MADHYA PRADESH', 'KARNATAKA', 'BIHAR',
       'WEST BENGAL', 'UTTAR PRADESH', 'PUNJAB', 'MAHARASHTRA', 'ODISHA',
       'HIMACHAL PRADESH', 'MEGHALAYA', 'KERALA', 'HARYANA', 'DELHI',
       'ANDHRA PRADESH', 'MANIPUR', 'RAJASTHAN', 'ASSAM',
       'ARUNACHAL PRADESH', 'JHARKHAND', 'GUJARAT', 'TRIPURA',
       'CHHATTISGARH', 'UTTARAKHAND', 'NAGALAND', 'SIKKIM', 'GOA',
       'PUDUCHERRY'], dtype=object)

In [14]:
from sklearn.preprocessing import LabelEncoder

data = train_data['state']

label_encoder = LabelEncoder()

train_data['state'] = label_encoder.fit_transform(data) + 1

print(train_data['state'].unique())

[24 14 12  4 28 26 21 15 19 10 17 13  9  6  1 16 22  3  2 11  8 25  5 27
 18 23  7 20]


In [15]:
train_data['state'].dtype

dtype('int64')

In [16]:
data = train_data['Party']
train_data['Party'] = label_encoder.fit_transform(data) + 1
print(train_data['Party'].unique())

[ 8  5  9  3  1 19 16  4 10 18 17 23  2  7 14 21 15  6 20 12 13 11 22]


In [17]:
train_data = train_data.rename(columns={'Constituency ∇': 'Constituency'})

In [18]:
data = train_data['Constituency']
train_data['Constituency'] = label_encoder.fit_transform(data) + 1
print(train_data['Constituency'].unique())

[  77  890 1105 ... 1219 1747 1862]


In [19]:
train_data.isnull().sum()

ID                0
Candidate         0
Constituency      0
Party             0
Criminal Case     0
Total Assets      0
Liabilities       0
state             0
Education         0
Debt Ratio       42
dtype: int64

In [20]:
train_data['Debt Ratio'].unique()

array([1.05500000e+02,            inf, 3.18181818e+01, 3.75000000e+01,
       3.27868852e+00, 1.03448276e+01, 4.50000000e+00, 1.42857143e+01,
       1.10000000e+01, 0.00000000e+00, 3.50000000e+00, 3.00000000e+02,
       1.00000000e+02, 4.20000000e+02, 3.10000000e+02, 1.20000000e+01,
       2.50000000e+01, 1.19047619e+01, 2.25000000e+00, 1.70000000e+01,
       7.50000000e+01, 6.00000000e+00, 4.44444444e+01, 2.41176471e+00,
       1.02564103e+01, 2.30769231e+01, 2.06896552e+01, 1.50000000e+00,
       1.12500000e+02, 1.05000000e+01, 3.33333333e+00, 1.28571429e+00,
       2.11111111e+02, 1.07142857e+01, 8.00000000e+02, 2.14285714e+01,
       2.70270270e+00, 5.70000000e+00, 1.06382979e+01, 3.04347826e+01,
       2.00000000e+02, 6.66666667e+01, 1.11111111e+01, 1.28571429e+01,
       5.66666667e+00, 1.13207547e+01, 8.00000000e+00, 1.86666667e+01,
       1.13636364e+01, 6.66666667e+02, 5.00000000e+00, 3.00000000e+01,
       1.33333333e+01, 2.85714286e+01, 3.66666667e+00, 2.50000000e+00,
      

In [21]:
ranges = [
    (0, 1000000),
    (1000001, 10000000),
    (10000001, 100000000),
    (100000001, 1000000000),
    (1000000001, np.inf)
]

def assign_range(val):
    for i, (start, end) in enumerate(ranges):
        if start <= val <= end:
            return f'Range {i+1}'

In [22]:
train_data['Total Assets'] = [assign_range(val) for val in train_data['Total Assets']]

In [23]:
train_data['Total Assets'].unique()

array(['Range 5', 'Range 2', 'Range 3', 'Range 4', 'Range 1'],
      dtype=object)

In [24]:
train_data['Liabilities'] = [assign_range(val) for val in train_data['Liabilities']]

In [25]:
data = train_data['Liabilities']
label_encoder = LabelEncoder()
train_data['Liabilities'] = label_encoder.fit_transform(data) + 1
print(train_data['Liabilities'].unique())

[3 1 2 4 5]


In [26]:
data = train_data['Total Assets']
label_encoder = LabelEncoder()
train_data['Total Assets'] = label_encoder.fit_transform(data) + 1
print(train_data['Total Assets'].unique())

[5 2 3 4 1]


In [27]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

X = train_data.drop(['Education','ID', 'Candidate', 'Constituency','Debt Ratio'], axis=1)  
y = train_data['Education']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=90)

# Define the parameter grid
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11],  # Different values of K
    'weights': ['uniform', 'distance'],  # Different weight functions
    'p': [1, 2],  # Different Minkowski distance metrics
}

# Initialize KNN classifier
knn_classifier = KNeighborsClassifier()

# Initialize GridSearchCV
grid_search = GridSearchCV(knn_classifier, param_grid, cv=5)

# Fit the GridSearchCV object to the data
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_
print("Best Parameters:", best_params)

Best Parameters: {'n_neighbors': 11, 'p': 1, 'weights': 'uniform'}


In [28]:
X = train_data.drop(['Education','ID', 'Candidate', 'Constituency','Debt Ratio'], axis=1)  
y = train_data['Education']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=90)

knn_classifier = KNeighborsClassifier(n_neighbors = 11, p = 1, weights = 'uniform')  # Initialize KNN classifier with 5 neighbors

knn_classifier.fit(X, y)  

#y_pred = knn_classifier.predict(X_test)

#accuracy = accuracy_score(y_test, y_pred)
#print("Accuracy:", accuracy * 100, "%")

#f1 = f1_score(y_test, y_pred, average='weighted')
#print("F1 score on test set:", f1)

KNeighborsClassifier(n_neighbors=11, p=1)

In [29]:
test_data = pd.read_csv("/kaggle/input/who-is-the-real-winner/test.csv")

In [30]:
data1 = test_data['Total Assets']
test_data['Total Assets'] = [convert_to_numeric(value) for value in data1]
data2 = test_data['Liabilities']
test_data['Liabilities'] = [convert_to_numeric(value) for value in data2]

In [31]:
test_data['Debt Ratio']  = test_data['Total Assets']/test_data['Liabilities']

In [32]:
data = test_data['state']
label_encoder = LabelEncoder()
test_data['state'] = label_encoder.fit_transform(data) + 1
print(test_data['state'].unique())

[15 28 26  2 22 19  8 24 10 14 11 27 21  5  6 12 18 13  1  4 16  3  9 25
 17  7 23 20]


In [33]:
data = test_data['Party']
test_data['Party'] = label_encoder.fit_transform(data) + 1
print(test_data['Party'].unique())

[10  3 14 19  5  4  2 18  8  9  1 12  7 23 17 13 16 15 20 22 21 11  6]


In [34]:
test_data = test_data.rename(columns={'Constituency ∇': 'Constituency'})

In [35]:
data = test_data['Constituency']
test_data['Constituency'] = label_encoder.fit_transform(data) + 1
print(test_data['Constituency'].unique())

[ 835 1191 1311 ...  958  774  222]


In [36]:
test_data['Total Assets'] = [assign_range(val) for val in test_data['Total Assets']]

In [37]:
test_data['Liabilities'] = [assign_range(val) for val in test_data['Liabilities']]

In [38]:
data = test_data['Liabilities']
label_encoder = LabelEncoder()
test_data['Liabilities'] = label_encoder.fit_transform(data) + 1
print(test_data['Liabilities'].unique())

[4 2 1 3 5]


In [39]:
data = test_data['Total Assets']
label_encoder = LabelEncoder()
test_data['Total Assets'] = label_encoder.fit_transform(data) + 1
print(test_data['Total Assets'].unique())

[4 3 2 1 5]


In [40]:
test = test_data.drop(['ID', 'Candidate','Constituency','Debt Ratio'], axis=1)

In [41]:
y_prediction = knn_classifier.predict(test)

In [42]:
res = pd.DataFrame(y_prediction)

In [43]:
res.columns = ['Education']

In [44]:
y1 = pd.DataFrame(test_data['ID'])

In [45]:
y1['Education'] = res['Education']
y1.reset_index(drop=True, inplace=True)

In [46]:
y1.to_csv('/kaggle/working/submission.csv',index=False)